version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false --local
    post_install:
      - poetry install --only docs --no-interaction --no-root

python:
  install: []

sphinx:
  configuration: docs/source/conf.py
